GET http://localhost:3000

###

POST http://localhost:3000
Content-Type: application/json
Accept: application/json

{
    "todo": "Belajar Node JS"
}

###

PUT http://localhost:3000
Content-Type: application/json
Accept: application/json

{
    "id": 2,
    "todo": "Belajar JS REST API"
}

###

DELETE  http://localhost:3000
Content-Type: application/json
Accept: application/json

{
    "id": 0
}